### PR TITLE
2p only conversion

### PR DESCRIPTION
**Pull request by alessandratrapani**
Add all the data streams that are common to #1 
- [x] add TTL signals
- [x] add wheel signals
- [x] add visual stimulus
- [ ] add Facemap output (after fixing #19) --> I will do a follow up PR
- [x] add Video recording
- [x] align all interfaces

### CODE REVIEW

**Comment by alessandratrapani** [comment]
stb nwb file [here](https://catalystneuro-processing.s3.us-east-2.amazonaws.com/higley-lab-to-nwb/04072021_am2psi_05_spont.nwb)

**Comment by weiglszonja** [comment]
The wheel signal looks flat for this short segment, is it ok for the whole recording?

**Review by weiglszonja — APPROVED** [review]
Comment on the wheel signal, others look good.

**Comment by alessandratrapani** [comment]
> The wheel signal looks flat for this short segment, is it ok for the whole recording?

I don't know what went wrong here, but I re-run it and now it looks like this:
image

**Comment by weiglszonja** [comment]
Yeah I'm seeing this in neurosift:
Screenshot 2024-06-11 at 13 34 17

**Comment by alessandratrapani** [comment]
> Yeah I'm seeing this in neurosift: Screenshot 2024-06-11 at 13 34 17

Let me update the file

**Comment by alessandratrapani** [comment]
update version [here](https://catalystneuro-processing.s3.us-east-2.amazonaws.com/higley-lab-to-nwb/04072021_am2psi_05_spont.nwb)

**Comment by weiglszonja** [comment]
> update version [here](https://catalystneuro-processing.s3.us-east-2.amazonaws.com/higley-lab-to-nwb/04072021_am2psi_05_spont.nwb)

Is it showing up differently for you in neurosift?

**Comment by alessandratrapani** [comment]
> > update version [here](https://catalystneuro-processing.s3.us-east-2.amazonaws.com/higley-lab-to-nwb/04072021_am2psi_05_spont.nwb)
> 
> Is it showing up differently for you in neurosift?

I see, it's just a scale thing. The actual signal is probably saturated in the first 100 frames, but then it looks like this:
image

**Comment by weiglszonja** [comment]
I see, ok then. there's a conflict now with the converter but otherwise feel free to merge this as well

**Pull request merged**
